### ISSUE TITLE
yara compile error

### ISSUE THREAD

**Issue by grayguest** [G4rb3n/Script-Ganker#1]
```
Traceback (most recent call last):
  File "script_ganker.py", line 135, in <module>
    family_name = yara_scan(script_path)
  File "script_ganker.py", line 28, in yara_scan
    yararule = yara.compile(filepaths=file_path)
  File "/home/mint64/python/Script-Ganker/venv/lib/python3.6/site-packages/yara/rules.py", line 465, in compile
    c = rules.context
  File "/home/mint64/python/Script-Ganker/venv/lib/python3.6/site-packages/yara/rules.py", line 240, in context
    c = RuleContext(*self._context_args)
  File "/home/mint64/python/Script-Ganker/venv/lib/python3.6/site-packages/yara/rules.py", line 61, in __init__
    raise exc
yara.libyara_wrapper.YaraSyntaxError: rule_db/chongfu.yar:10: duplicate metadata identifier "md5_2008"
rule_db/teamtnt.yar:56: illegal escape sequence
rule_db/sysrv_hello.yar:10: duplicate metadata identifier "md5_2101"
```

**Comment by hzzhero** [comment]
try to install yara-python instead of yara @grayguest
